### ISSUE TITLE
关于链接

### ISSUE THREAD

**Issue by nankaine** [WShihan/blblcd#1]
你好，试了一下，无法抓取到评论插入URL吗

**Comment by WShihan** [comment]
> 你好，试了一下，无法抓取到评论插入URL吗

抱歉，我没有明白你的意思，可以描述得更详细一些吗？

**Comment by WShihan** [comment]
获取的评论仅包含文本内容，刚修改增加一个功能——获取图片链接另写入csv字段并自动下载图片到本地。
