### ISSUE TITLE
默认隐藏的评论，需要点击才出现的，不能爬吗

### ISSUE THREAD

**Issue by MrMingFang** [WShihan/blblcd#4]
<img width="1066" alt="image" src="https://github.com/user-attachments/assets/77a96420-c9ed-4861-8b0d-b67f93c37012">

**Comment by WShihan** [comment]
目前是的，将标记该问题，日后解决。

**Comment by yukminnie** [comment]
好吧，我说怎么点开结果，感觉少了好些😓。

**Comment by WShihan** [comment]
已修改。
