### ISSUE TITLE
爬取是乱码

### ISSUE THREAD

**Issue by pukrr** [WShihan/blblcd#5]
现在还能用吗？爬取的评论是乱码是怎么回事，只有一条还是乱码

**Comment by WShihan** [comment]
可以正常使用。乱码，什么平台？请提供一些详细信息。

**Comment by WShihan** [comment]
爬取之后保存的csv文件编码为utf8，使用诸如MS Office之类的软件打开会显示乱码，可以选择纯文本软件如笔记本打开。
