### ISSUE TITLE
你好，这个具体怎么使用啊，在哪个文件夹打开终端输入指令

### ISSUE THREAD

**Issue by zhaohao-max** [WShihan/blblcd#6]
**描述问题｜Bug Description**
清晰简洁地描述您遇到的问题｜Describe the issue you are encountering clearly and concisely.

**重现步骤｜Reproduction Step**

1. 步骤 1 ｜step 1
2. 步骤 2 ｜step2
3. 步骤 3｜step3
4. 看到的结果 ｜ what's you  got
5. 

**预期结果｜Expectation**
您期望看到的结果是什么？｜What's your expectation ?

**截图｜Snapshot**
如果适用，请附上截图以帮助解释您的问题。｜Provide snapshots if possible.

**环境｜Environment**

- 操作系统｜OS：例如  Windows 10, macOS 11.2
- 版本｜Version：例如 1.0.0

**Comment by WShihan** [comment]
你好：
步骤如下，
1.前往【release】页面，找到编译好的二进制文件
<img width="1437" alt="image" src="https://github.com/user-attachments/assets/7c553960-20ed-45dc-a7ba-def6bb518ad5">

2.根据你电脑的操作系统选择对应的二进制文件，然后下载，解压
![os](https://github.com/user-attachments/assets/40963a1b-2b54-45cf-8528-6729b4f5d721)

3.接着在文件所在目录下，进入终端程序（不同操作系统，操作会有不同），执行命令，例如如果你是windows系统，可以输入如下命令查看工具所有的命令列表。
```bash
blblcd_0_0_4_1_windows_amd64.exe -h

```
针对每一个命令，在项目README里有详细介绍，详见。
