### ISSUE TITLE
[BUG] 脚本无法使用

### ISSUE THREAD

**Issue by bgzhang1** [WShihan/blblcd#8]
**描述问题｜Bug Description**
清晰简洁地描述您遇到的问题｜Describe the issue you are encountering clearly and concisely.

**重现步骤｜Reproduction Step**

1. 步骤 1 ｜step 1 使用命令.\blblcd_0_0_4_1_windows_amd64.exe -bvid BV1yRiBYjEfp -cookie cookie.txt
2. 看到的结果 ｜ what's you  got
2024/12/13 23:21:11 INFO 完成评论获取，oid: 113605106211175, 第2页
2024/12/13 23:21:13 INFO 爬取视频子评论113605106211175
2024/12/13 23:21:14 INFO 完成子评论获取，oid: 113605106211175, 第1页
2024/12/13 23:21:15 INFO 爬取视频子评论113605106211175
2024/12/13 23:21:16 INFO 完成子评论获取，oid: 113605106211175, 第2页
2024/12/13 23:21:17 INFO 爬取视频子评论113605106211175
2024/12/13 23:21:18 INFO 完成子评论获取，oid: 113605106211175, 第3页
2024/12/13 23:21:18 INFO ******视频113605106211175，第4页未获取到子评论，停止爬取******
2024/12/13 23:21:19 INFO 爬取视频子评论113605106211175
2024/12/13 23:21:19 INFO 完成子评论获取，oid: 113605106211175, 第1页
2024/12/13 23:21:21 INFO 爬取视频子评论113605106211175
2024/12/13 23:21:21 INFO 完成子评论获取，oid: 113605106211175, 第2页
2024/12/13 23:21:23 INFO 爬取视频子评论113605106211175
2024/12/13 23:21:23 INFO 完成子评论获取，oid: 113605106211175, 第3页
2024/12/13 23:21:23 INFO ******视频113605106211175，第4页未获取到子评论，停止爬取******
陷入死循环
有一次运行时显示2024/12/13 23:21:09 INFO 写入csv文件成功，oid:113605106211175,在output中查看输出文档发现为乱码
**预期结果｜Expectation**
您期望看到的结果是什么？｜What's your expectation ?

**截图｜Snapshot**
如果适用，请附上截图以帮助解释您的问题。｜Provide snapshots if possible.

**环境｜Environment**

- 操作系统｜OS：例如  windows11 24H2
- 版本｜Version：例如 0.0.4.1

**Comment by bgzhang1** [comment]
更换目标视频为BV1GWBgYQEgE后发现又可以使用

**Comment by bgzhang1** [comment]
怀疑是重试机制出现问题，使用https://github.com/1837669410/bilibili_comment_crawl的脚本可以正常获取评论

**Comment by WShihan** [comment]
你好
       按热度爬取，前面循环出现的是子评论页码，非陷入死循环。

祝好！
